language: python

python:
    - "2.7"

env:
    - DJANGO=1.9 DB=postgres

cache:
    - pip

install:
    - pip install pipenv
    - pipenv install --dev --deploy

before_script:
    - createuser --createdb django_oauth2_server
    - createdb -U django_oauth2_server django_oauth2_server
    - cp oauth2server/proj/settings/local.example.py oauth2server/proj/settings/local.py
    - pipenv run oauth2server/manage.py migrate
    - pipenv run oauth2server/manage.py collectstatic --noinput;

script:
    - pipenv run oauth2server/manage.py test

branches:
    only:
        - master
