version: '2'

services:
  postgres:
    container_name: postgres
    image: sdcplatform/postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  oauth2-service:
    container_name: oauth2-service
    build: ./
    restart: always
    depends_on:
      - postgres
    ports:
      - "8040:8040"