# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-07 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthaccesstoken',
            options={'ordering': ['-access_token'], 'verbose_name_plural': 'Access Tokens for OAuth Server'},
        ),
        migrations.AlterModelOptions(
            name='oauthauthorizationcode',
            options={'ordering': ['-code'], 'verbose_name_plural': 'Access Codes (used to obtain tokens)'},
        ),
        migrations.AlterModelOptions(
            name='oauthrefreshtoken',
            options={'ordering': ['-refresh_token'], 'verbose_name_plural': 'Refresh Token for OAuth Server'},
        ),
        migrations.AlterModelOptions(
            name='oauthscope',
            options={'ordering': ['-scope'], 'verbose_name_plural': 'Scope (roles) for OAuth Server'},
        ),
    ]
