# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-31 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_auto_20170330_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthuser',
            name='failed_logins',
            field=models.IntegerField(default=0),
        ),
    ]
