# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-31 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_oauthuser_failed_logins'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthuser',
            name='account_is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
