# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-07 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_oauthuser_account_is_locked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthclient',
            options={'ordering': ['-client_id'], 'verbose_name_plural': 'Client Identifiers for OAuth Server'},
        ),
        migrations.AlterModelOptions(
            name='oauthuser',
            options={'ordering': ['-email'], 'verbose_name_plural': 'Users of OAuth Server'},
        ),
        migrations.AddField(
            model_name='oauthuser',
            name='account_is_verified',
            field=models.BooleanField(default=False, help_text=b'This indicates if the account has been verified'),
        ),
        migrations.AlterField(
            model_name='oauthuser',
            name='account_is_locked',
            field=models.BooleanField(default=False, help_text=b'This indicates if the account is locked'),
        ),
        migrations.AlterField(
            model_name='oauthuser',
            name='failed_logins',
            field=models.IntegerField(default=0, help_text=b'How many consecutive times a user has used the wrong password'),
        ),
    ]
