# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-14 16:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0005_auto_20170407_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthclient',
            name='client_id',
            field=models.CharField(help_text='This is a unique string used to identify the client', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='oauthclient',
            name='redirect_uri',
            field=models.URLField(default='http://www.example.com', help_text='This is a unique URI to describe the callback used by the OAuth2 server', max_length=254, validators=[django.core.validators.URLValidator]),
        ),
        migrations.AlterField(
            model_name='oauthuser',
            name='account_is_locked',
            field=models.BooleanField(default=False, help_text='This indicates if the account is locked'),
        ),
        migrations.AlterField(
            model_name='oauthuser',
            name='account_is_verified',
            field=models.BooleanField(default=False, help_text='This indicates if the account has been verified'),
        ),
        migrations.AlterField(
            model_name='oauthuser',
            name='failed_logins',
            field=models.IntegerField(default=0, help_text='How many consecutive times a user has used the wrong password'),
        ),
    ]
